service:
  concept: エンジニアを目指す全ての人のための学びのプラットフォーム
  welcome_tagline: 小さな努力の積み上げで、見たこともない自分に出会おう。
  portfolio_tagline: みんなのポートフォリオを覗いてみよう
  study_time_tagline: 勉強時間を管理してモチベーションに繋げよう
  book_tagline: Study Stash開発者おすすめの書籍
  article_tagline: 最新記事はこちら